server:
  port: 9002
  
spring:
  application:
    name: STUDENT-SERVICE
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
springdoc:
  swagger-ui:
    enabled: true
    
---


server:
  port: 9003
  
spring:
  config:
    activate:
      on-profile:
      - dev
  application:
    name: STUDENT-SERVICE
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
